/* Drink database.
 * Values are approximate caffeine amounts compiled from brand nutrition pages and
 * public caffeine references. Rows: [name, category, serving fl oz, mg, extra?].
 * Category is one of coffee | tea | energy | soda | other.
 * extra (optional): { unit: 'pouch' | 'pill' | ..., substance: 'paraxanthine' }.
 * Rows without a substance are caffeine.
 */
(function () {
  'use strict';

  var PILL = { unit: '1 pill' };
  var MINT = { unit: '1 mint' };
  var POUCH = { unit: '1 pouch' };
  var PX_POUCH = { unit: '1 pouch', substance: 'paraxanthine' };

  var FEATURED = [
    // Personal staples
    ['Caffeine Pill (100 mg)', 'other', 0, 100, PILL],
    ['Caffeine Mint (80 mg)', 'other', 0, 80, MINT],
    ['Ultra Energy Pouch', 'other', 0, 180, POUCH],
    ['Ultra Focus Pouch (Paraxanthine)', 'other', 0, 100, PX_POUCH],
    // CafTrack's default favorites
    ['Brewed Coffee (8 oz)', 'coffee', 8, 95],
    ['Latte (8 oz)', 'coffee', 8, 63],
    ['Black Tea (8 oz)', 'tea', 8, 47],
    ['Red Bull (8.4 oz)', 'energy', 8.4, 80],
    ['Celsius (12 oz)', 'energy', 12, 200]
  ];

  var ROWS = [
    // ---- Coffee: generic ----
    ['Brewed Coffee', 'coffee', 8, 95],
    ['Brewed Coffee', 'coffee', 12, 142],
    ['Brewed Coffee', 'coffee', 16, 190],
    ['Brewed Coffee', 'coffee', 20, 237],
    ['Espresso (Single Shot)', 'coffee', 1, 64],
    ['Espresso (Double Shot)', 'coffee', 2, 128],
    ['Espresso (Triple Shot)', 'coffee', 3, 192],
    ['Ristretto', 'coffee', 0.75, 55],
    ['Lungo', 'coffee', 3, 80],
    ['Americano', 'coffee', 12, 128],
    ['Americano', 'coffee', 16, 192],
    ['Latte', 'coffee', 12, 128],
    ['Latte', 'coffee', 16, 128],
    ['Iced Latte', 'coffee', 16, 128],
    ['Cappuccino', 'coffee', 8, 64],
    ['Cappuccino', 'coffee', 12, 128],
    ['Flat White', 'coffee', 12, 130],
    ['Cortado', 'coffee', 4.5, 128],
    ['Macchiato (Espresso)', 'coffee', 2, 64],
    ['Mocha', 'coffee', 12, 128],
    ['Breve', 'coffee', 12, 128],
    ['Red Eye', 'coffee', 12, 159],
    ['Black Eye', 'coffee', 12, 223],
    ['Cafe au Lait', 'coffee', 12, 95],
    ['Affogato', 'coffee', 4, 64],
    ['Cold Brew', 'coffee', 12, 155],
    ['Cold Brew', 'coffee', 16, 205],
    ['Nitro Cold Brew', 'coffee', 16, 265],
    ['Iced Coffee', 'coffee', 16, 165],
    ['Instant Coffee', 'coffee', 8, 62],
    ['Decaf Coffee', 'coffee', 8, 2],
    ['Decaf Espresso', 'coffee', 1, 3],
    ['Turkish Coffee', 'coffee', 2, 50],
    ['French Press Coffee', 'coffee', 8, 107],
    ['Pour Over Coffee', 'coffee', 8, 110],
    ['Moka Pot Coffee', 'coffee', 2, 105],
    ['AeroPress Coffee', 'coffee', 8, 110],
    ['Vietnamese Iced Coffee', 'coffee', 8, 150],
    ['Irish Coffee', 'coffee', 8, 60],
    ['Frappe (Blended Coffee)', 'coffee', 16, 95],
    ['Dalgona Coffee', 'coffee', 8, 60],
    ['Cuban Coffee (Cafecito)', 'coffee', 2, 100],
    ['K-Cup Coffee Pod', 'coffee', 8, 100],
    ['K-Cup Extra Bold Pod', 'coffee', 8, 120],
    ['Nespresso Original Capsule', 'coffee', 1.35, 60],
    ['Nespresso Vertuo Coffee', 'coffee', 7.8, 200],
    ['Nespresso Vertuo Double Espresso', 'coffee', 2.7, 130],
    ['Nespresso Vertuo Gran Lungo', 'coffee', 5, 150],
    ['Death Wish Coffee', 'coffee', 12, 472],
    ['Black Rifle Coffee (Brewed)', 'coffee', 12, 140],
    ['Jot Ultra Coffee (1 tbsp)', 'coffee', 0.5, 150],

    // ---- Coffee: Starbucks ----
    ['Starbucks Pike Place Roast Short', 'coffee', 8, 155],
    ['Starbucks Pike Place Roast Tall', 'coffee', 12, 235],
    ['Starbucks Pike Place Roast Grande', 'coffee', 16, 310],
    ['Starbucks Pike Place Roast Venti', 'coffee', 20, 410],
    ['Starbucks Blonde Roast Grande', 'coffee', 16, 360],
    ['Starbucks Dark Roast Grande', 'coffee', 16, 260],
    ['Starbucks Decaf Pike Place Grande', 'coffee', 16, 25],
    ['Starbucks Espresso Solo', 'coffee', 1, 75],
    ['Starbucks Espresso Doppio', 'coffee', 2, 150],
    ['Starbucks Caffe Americano Tall', 'coffee', 12, 150],
    ['Starbucks Caffe Americano Grande', 'coffee', 16, 225],
    ['Starbucks Caffe Americano Venti', 'coffee', 20, 300],
    ['Starbucks Caffe Latte Tall', 'coffee', 12, 75],
    ['Starbucks Caffe Latte Grande', 'coffee', 16, 150],
    ['Starbucks Caffe Latte Venti', 'coffee', 20, 150],
    ['Starbucks Cappuccino Grande', 'coffee', 16, 150],
    ['Starbucks Caramel Macchiato Grande', 'coffee', 16, 150],
    ['Starbucks Flat White Grande', 'coffee', 16, 195],
    ['Starbucks Caffe Mocha Grande', 'coffee', 16, 175],
    ['Starbucks White Chocolate Mocha Grande', 'coffee', 16, 150],
    ['Starbucks Pumpkin Spice Latte Grande', 'coffee', 16, 150],
    ['Starbucks Cold Brew Grande', 'coffee', 16, 205],
    ['Starbucks Cold Brew Venti', 'coffee', 24, 310],
    ['Starbucks Nitro Cold Brew Grande', 'coffee', 16, 265],
    ['Starbucks Vanilla Sweet Cream Cold Brew Grande', 'coffee', 16, 185],
    ['Starbucks Iced Coffee Grande', 'coffee', 16, 165],
    ['Starbucks Iced Shaken Espresso Grande', 'coffee', 16, 255],
    ['Starbucks Brown Sugar Oatmilk Shaken Espresso Grande', 'coffee', 16, 255],
    ['Starbucks Coffee Frappuccino Grande', 'coffee', 16, 90],
    ['Starbucks Mocha Frappuccino Grande', 'coffee', 16, 100],
    ['Starbucks Caramel Frappuccino Grande', 'coffee', 16, 90],
    ['Starbucks Doubleshot Espresso (Can)', 'coffee', 6.5, 120],
    ['Starbucks Bottled Frappuccino', 'coffee', 13.7, 110],
    ['Starbucks Canned Nitro Cold Brew', 'coffee', 9.6, 235],
    ['Starbucks VIA Instant Packet', 'coffee', 8, 135],
    ['Starbucks Chai Tea Latte Grande', 'tea', 16, 95],
    ['Starbucks Matcha Tea Latte Grande', 'tea', 16, 80],
    ['Starbucks Pink Drink Grande', 'other', 16, 45],
    ['Starbucks Strawberry Acai Refresher Grande', 'other', 16, 45],
    ['Starbucks Tripleshot Energy', 'energy', 15, 225],
    ['Starbucks Doubleshot Energy', 'energy', 15, 145],
    ['Starbucks Baya Energy', 'energy', 12, 160],

    // ---- Coffee: other chains & bottled ----
    ['Dunkin Hot Coffee Small', 'coffee', 10, 150],
    ['Dunkin Hot Coffee Medium', 'coffee', 14, 210],
    ['Dunkin Hot Coffee Large', 'coffee', 20, 300],
    ['Dunkin Hot Coffee Extra Large', 'coffee', 24, 359],
    ['Dunkin Iced Coffee Medium', 'coffee', 24, 297],
    ['Dunkin Cold Brew Medium', 'coffee', 24, 347],
    ['Dunkin Latte Medium', 'coffee', 14, 166],
    ['Dunkin Americano Medium', 'coffee', 14, 284],
    ['Dunkin Espresso Shot', 'coffee', 1.3, 118],
    ['Dunkin Refresher Medium', 'other', 24, 99],
    ['McDonald\'s McCafe Premium Roast Small', 'coffee', 12, 109],
    ['McDonald\'s McCafe Premium Roast Medium', 'coffee', 16, 145],
    ['McDonald\'s McCafe Premium Roast Large', 'coffee', 21, 180],
    ['McDonald\'s McCafe Latte Medium', 'coffee', 16, 142],
    ['McDonald\'s Iced Coffee Medium', 'coffee', 22, 133],
    ['McDonald\'s Mocha Frappe Medium', 'coffee', 16, 125],
    ['Tim Hortons Original Blend Small', 'coffee', 10, 140],
    ['Tim Hortons Original Blend Medium', 'coffee', 14, 205],
    ['Tim Hortons Original Blend Large', 'coffee', 20, 270],
    ['Peet\'s Coffee Medium', 'coffee', 16, 267],
    ['La Colombe Draft Latte', 'coffee', 9, 120],
    ['La Colombe Triple Draft Latte', 'coffee', 9, 180],
    ['Java Monster', 'coffee', 15, 188],
    ['Java Monster 300', 'coffee', 15, 300],
    ['High Brew Cold Brew', 'coffee', 8, 150],
    ['Chameleon Cold Brew', 'coffee', 10, 270],
    ['Stok Cold Brew (Black)', 'coffee', 13.7, 145],

    // ---- Tea ----
    ['Black Tea', 'tea', 8, 47],
    ['Black Tea', 'tea', 16, 94],
    ['Green Tea', 'tea', 8, 28],
    ['Green Tea', 'tea', 16, 56],
    ['White Tea', 'tea', 8, 25],
    ['Oolong Tea', 'tea', 8, 37],
    ['Earl Grey Tea', 'tea', 8, 50],
    ['English Breakfast Tea', 'tea', 8, 47],
    ['Darjeeling Tea', 'tea', 8, 50],
    ['Assam Tea', 'tea', 8, 60],
    ['Jasmine Tea', 'tea', 8, 25],
    ['Sencha', 'tea', 8, 30],
    ['Genmaicha', 'tea', 8, 20],
    ['Hojicha', 'tea', 8, 8],
    ['Pu-erh Tea', 'tea', 8, 60],
    ['Matcha (1 tsp)', 'tea', 8, 70],
    ['Matcha Latte', 'tea', 12, 80],
    ['Chai Tea', 'tea', 8, 47],
    ['Chai Latte', 'tea', 12, 70],
    ['Iced Tea (Brewed)', 'tea', 16, 70],
    ['Sweet Tea', 'tea', 16, 60],
    ['Bubble Tea (Milk Tea)', 'tea', 16, 60],
    ['Thai Iced Tea', 'tea', 12, 50],
    ['Decaf Tea', 'tea', 8, 2],
    ['Herbal Tea', 'tea', 8, 0],
    ['Rooibos Tea', 'tea', 8, 0],
    ['Yerba Mate (Brewed)', 'tea', 8, 80],
    ['Guayaki Yerba Mate (Can)', 'tea', 15.5, 150],
    ['Kombucha', 'tea', 8, 15],
    ['Snapple Lemon Tea', 'tea', 16, 37],
    ['Pure Leaf Sweet Tea', 'tea', 18.5, 55],
    ['Pure Leaf Unsweetened Black Tea', 'tea', 18.5, 60],
    ['Gold Peak Sweet Tea', 'tea', 18.5, 47],
    ['Lipton Iced Tea (Bottle)', 'tea', 20, 38],
    ['AriZona Green Tea', 'tea', 23, 45],
    ['AriZona Lemon Iced Tea', 'tea', 23, 45],
    ['Honest Tea Half Tea & Half Lemonade', 'tea', 16.9, 50],

    // ---- Energy drinks ----
    ['Red Bull', 'energy', 8.4, 80],
    ['Red Bull', 'energy', 12, 114],
    ['Red Bull', 'energy', 16, 151],
    ['Red Bull', 'energy', 20, 189],
    ['Red Bull Sugarfree', 'energy', 8.4, 80],
    ['Red Bull Zero', 'energy', 8.4, 80],
    ['Red Bull Editions', 'energy', 12, 114],
    ['Monster Energy', 'energy', 16, 160],
    ['Monster Energy Zero Ultra', 'energy', 16, 150],
    ['Monster Energy Ultra (Any Flavor)', 'energy', 16, 150],
    ['Monster Rehab', 'energy', 15.5, 160],
    ['Monster Juice', 'energy', 16, 160],
    ['Monster Reserve', 'energy', 16, 160],
    ['Monster Nitro', 'energy', 16, 160],
    ['Monster Mega', 'energy', 24, 240],
    ['Monster Hydro', 'energy', 25.4, 188],
    ['Monster Energy (500 ml)', 'energy', 16.9, 160],
    ['Rockstar Original', 'energy', 16, 160],
    ['Rockstar Pure Zero', 'energy', 16, 240],
    ['Rockstar Punched', 'energy', 16, 240],
    ['Bang Energy', 'energy', 16, 300],
    ['Reign Total Body Fuel', 'energy', 16, 300],
    ['Reign Storm', 'energy', 12, 200],
    ['Celsius', 'energy', 12, 200],
    ['Celsius Heat', 'energy', 16, 300],
    ['Celsius Essentials', 'energy', 16, 270],
    ['GHOST Energy', 'energy', 16, 200],
    ['C4 Energy', 'energy', 16, 200],
    ['C4 Smart Energy', 'energy', 12, 200],
    ['C4 Ultimate', 'energy', 16, 300],
    ['Alani Nu Energy', 'energy', 12, 200],
    ['Prime Energy', 'energy', 12, 200],
    ['3D Energy', 'energy', 16, 200],
    ['ZOA Energy', 'energy', 16, 160],
    ['NOS Energy', 'energy', 16, 160],
    ['Full Throttle', 'energy', 16, 160],
    ['AMP Energy', 'energy', 16, 142],
    ['Venom Energy', 'energy', 16, 160],
    ['Xyience', 'energy', 16, 176],
    ['Rip It', 'energy', 16, 200],
    ['Guru Organic Energy', 'energy', 12, 142],
    ['Uptime Energy', 'energy', 12, 142],
    ['Kill Cliff Ignite', 'energy', 12, 150],
    ['Raze Energy', 'energy', 16, 300],
    ['Bucked Up Energy', 'energy', 16, 300],
    ['Gorilla Mind Energy', 'energy', 16, 200],
    ['Adrenaline Shoc', 'energy', 16, 300],
    ['Bloom Energy', 'energy', 12, 180],
    ['Zevia Energy', 'energy', 12, 120],
    ['Coca-Cola Energy', 'energy', 12, 114],
    ['Aspire Energy', 'energy', 12, 80],
    ['Redline Xtreme', 'energy', 8, 316],
    ['Spike Hardcore Energy', 'energy', 16, 350],
    ['Relentless', 'energy', 16.9, 160],
    ['Lucozade Energy', 'energy', 12.8, 46],
    ['Mountain Dew Kickstart', 'energy', 16, 92],
    ['Mountain Dew Rise Energy', 'energy', 16, 180],
    ['Mountain Dew Game Fuel', 'energy', 16, 90],
    ['5-hour Energy Shot', 'energy', 1.93, 200],
    ['5-hour Energy Extra Strength', 'energy', 1.93, 230],
    ['Proper Wild Energy Shot', 'energy', 2.5, 180],
    ['Club-Mate', 'energy', 16.9, 100],

    // ---- Soda ----
    ['Coca-Cola Classic', 'soda', 12, 34],
    ['Coca-Cola Classic', 'soda', 20, 57],
    ['Coca-Cola Mini Can', 'soda', 7.5, 21],
    ['Diet Coke', 'soda', 12, 46],
    ['Diet Coke', 'soda', 20, 76],
    ['Coca-Cola Zero Sugar', 'soda', 12, 34],
    ['Cherry Coke', 'soda', 12, 34],
    ['Vanilla Coke', 'soda', 12, 34],
    ['Coca-Cola with Coffee', 'soda', 12, 69],
    ['Pepsi', 'soda', 12, 38],
    ['Pepsi', 'soda', 20, 63],
    ['Diet Pepsi', 'soda', 12, 35],
    ['Pepsi Zero Sugar', 'soda', 12, 69],
    ['Mountain Dew', 'soda', 12, 54],
    ['Mountain Dew', 'soda', 20, 91],
    ['Diet Mountain Dew', 'soda', 12, 54],
    ['Mountain Dew Zero Sugar', 'soda', 12, 68],
    ['Dr Pepper', 'soda', 12, 41],
    ['Dr Pepper', 'soda', 20, 68],
    ['Diet Dr Pepper', 'soda', 12, 41],
    ['Pibb Xtra', 'soda', 12, 40],
    ['Mello Yello', 'soda', 12, 51],
    ['Surge', 'soda', 16, 69],
    ['Barq\'s Root Beer', 'soda', 12, 22],
    ['Sunkist Orange', 'soda', 12, 19],
    ['A&W Cream Soda', 'soda', 12, 29],
    ['Zevia Cola', 'soda', 12, 45],
    ['Sprite', 'soda', 12, 0],
    ['7UP', 'soda', 12, 0],
    ['Fanta Orange', 'soda', 12, 0],
    ['Ginger Ale', 'soda', 12, 0],

    // ---- Other ----
    ['Dark Chocolate (1 oz)', 'other', 1, 24],
    ['Milk Chocolate Bar (1.55 oz)', 'other', 1.55, 9],
    ['Hot Chocolate', 'other', 8, 5],
    ['Chocolate Milk', 'other', 8, 5],
    ['Coffee Ice Cream (1/2 cup)', 'other', 4, 30],
    ['Chocolate-Covered Coffee Beans (10)', 'other', 0.5, 60],
    ['Tiramisu (1 slice)', 'other', 4, 30],
    ['Caffeine Pill (200 mg)', 'other', 0, 200, PILL],
    ['Caffeine Pill (50 mg)', 'other', 0, 50, PILL],
    ['NoDoz (1 tablet)', 'other', 0, 200],
    ['Caffeine Mint (40 mg)', 'other', 0, 40, MINT],
    ['Caffeine Pouch (100 mg)', 'other', 0, 100, POUCH],
    ['Caffeine Pouch (150 mg)', 'other', 0, 150, POUCH],
    ['Caffeine Pouch (180 mg)', 'other', 0, 180, POUCH],
    ['Ultra Focus Pouch (Pre-2026, 75 mg Paraxanthine)', 'other', 0, 75, PX_POUCH],
    ['Paraxanthine Capsule (200 mg)', 'other', 0, 200, { unit: '1 capsule', substance: 'paraxanthine' }],
    ['Excedrin Migraine (2 tablets)', 'other', 0, 130],
    ['Run Gum (1 piece)', 'other', 0, 50],
    ['Military Energy Gum (1 piece)', 'other', 0, 100],
    ['GU Energy Gel (Caffeinated)', 'other', 1.1, 20],
    ['Clif Bar (Cool Mint Chocolate)', 'other', 0, 50],
    ['Pre-Workout (1 scoop)', 'other', 0, 150],
    ['Awake Chocolate Bite', 'other', 0, 50]
  ];

  function slug(s) {
    return s.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  }

  function fmtOz(oz) {
    return Number.isInteger(oz) ? String(oz) : oz.toFixed(1).replace(/\.0$/, '');
  }

  var nameCounts = {};
  ROWS.forEach(function (r) { nameCounts[r[0]] = (nameCounts[r[0]] || 0) + 1; });

  function toDrink(row, prefix) {
    var name = row[0], category = row[1], oz = row[2], mg = row[3], extra = row[4] || {};
    var serving = oz > 0 ? { oz: oz, ml: Math.round(oz * 29.5735) } : null;
    // Names shared by several sizes get the size appended so they stay distinguishable.
    var displayName = !prefix && serving && nameCounts[name] > 1 ? name + ' (' + fmtOz(oz) + ' oz)' : name;
    var drink = {
      id: (prefix || '') + slug(name) + (serving ? '-' + serving.ml + 'ml' : ''),
      name: displayName,
      category: category,
      serving: serving,
      caffeineMg: mg
    };
    if (extra.unit) drink.unit = extra.unit;
    if (extra.substance) drink.substance = extra.substance;
    return drink;
  }

  window.CT = window.CT || {};
  window.CT.FEATURED_DRINKS = FEATURED.map(function (r) { return toDrink(r, 'featured-'); });
  window.CT.DRINKS = ROWS.map(function (r) { return toDrink(r, ''); });
})();
